[WIP] CM-242 GenerateMnemonic screen
ozalexo/ChronoMint-RN pull request #24
Opened 2018-11-16 11:32 UTC by e-molochko

2018-11-16 11:57 UTC, ozalexo requested changes
This page must be added into StoryBook.

2018-11-16 11:57 UTC, ozalexo commented on src/screens/Login/GenerateMnemonic/GenerateMnemonic.js
> +    {i18n.t(['GenerateMnemonic', 'warnings', warningIndex.toString(), 'content'])}
Please format code of WarningItem. Why ESlint did not warn you?

2018-11-19 07:29 UTC, ozalexo requested changes

2018-11-19 07:29 UTC, ozalexo commented on src/screens/Login/GenerateMnemonic/GenerateMnemonicStyles.js
> +    marginHorizontal: '20%',
It must be in pixels. Also it is better to use `paddingHorizonlal: 20` instead of marginHorizontal.

We should not use percents for heights or widths in such cases. Percents may be used for tables' columns, but we have no screens with tables.

2018-11-19 07:29 UTC, ozalexo commented on src/common/constants/screens.js
> +import normalize from '../utils/responseveSize'
Please rename `responseveSize` to `responosiveSize`.

2018-11-19 07:29 UTC, ozalexo commented on src/common/utils/responseveSize.js
> +const {width, height} = Dimensions.get('window');
Please remove ";" and add spaces before } and after {

2018-11-19 07:29 UTC, ozalexo commented on src/components/Input/InputStyles.js
>      width: '100%',
Let's replace all `width: N%` and `height: N%` to pure flex layout with no percents.

2018-11-19 07:29 UTC, ozalexo commented on src/navigation/LoginStack.js
> +        title: 'Confirm recovery phrase',
We need I18N translation here (and for all other screens' titles).

2018-11-19 07:29 UTC, ozalexo commented on src/screens/Login/ConfirmMnemonic/ConfirmMnemonic.js
> +  return (
Code style:
Let's add empty line before each return, as it was done in this file at lines 47-49

2018-11-19 07:29 UTC, ozalexo commented on src/common/utils/responseveSize.js
> +    return Math.round(PixelRatio.roundToNearestPixel(newSize)) - 2
Why "-2"? Please add a comment with explanation.

2018-11-19 07:38 UTC, ozalexo commented
Fix with 'normalize' does not work (iPhone 6, real):
![file](https://user-images.githubusercontent.com/661889/48692460-30976100-ebe7-11e8-93df-29af85c1deed.jpg)

2018-11-19 08:03 UTC, ozalexo commented on storybook/stories/index.js
> +      mnemonic='test mnemonick for story book'
Mnemonic phrase must contain exactly 12 words from dictionary. Please use one of generated mnemonic phrases for test purposes.

2018-11-19 08:03 UTC, ozalexo commented on storybook/stories/index.js
> +    <ConfitmMnemonic
Typo: Confitm -> Confirm

2018-11-19 08:05 UTC, ozalexo commented on storybook/stories/ConfitmMnemonic/index.js
> +/**
Typo in folder name: Confitm -> Confirm

2018-11-19 09:54 UTC, e-molochko commented on src/screens/Login/GenerateMnemonic/GenerateMnemonicStyles.js
> +    marginHorizontal: '20%',
I used margin here for button not to be full width and to have indents

2018-11-19 10:13 UTC, ozalexo commented on storybook/stories/index.js
>        mnemonic='check mnemonic phrase'
Also need 12 words. Use the same as at line 384 please

2018-11-19 14:21 UTC, ozalexo commented
There is an issue in iOS: extra space between header and scrollable content.
![file 1](https://user-images.githubusercontent.com/661889/48712692-76701b80-ec1f-11e8-94b3-2d44f2641fa0.jpg)

2018-11-20 10:22 UTC, ozalexo approved these changes
LGTM

2018-11-20 10:22 UTC, merged