[WIP] CM-249/ Store structure(session)
ozalexo/ChronoMint-RN pull request #26
Opened 2018-11-20 11:50 UTC by e-molochko

2018-11-20 12:02 UTC, ozalexo commented on src/redux/session/actions.js
> +    currentWallet: '',
I suggest to use null here. Empty string also falsy, but in this case we not handle error if we will have empty address for a reason.

2018-11-20 12:02 UTC, ozalexo commented on src/redux/session/constants.js
> +export const USER_ACTIONS = {
Let's define casual naming standard for action constants.

For DUCK session we need to use something like this:
```
export const SESSION_LOGIN = 'SESSION/LOGIN'
export const SESSION_LOGOUT = 'SESSION/LOGOUT'
```

So, it should has the following format: export const DUCKPREFIX_ACTION_TITLE = 'DUCKPREFIX/ACTION_TITLE'

2018-11-20 12:02 UTC, ozalexo commented on src/redux/session/initialState.js
> +    currentWallet: '',
See my previous comment about null and ''.

2018-11-20 12:02 UTC, ozalexo commented on src/redux/session/selectors.js
> +  (state) => state[DUCK_SESSION],
I suggest to make selector for each duck. 
```
import { DUCK_SESSION } from './constants'

const getDuckSession = (state) =>
  state[DUCK_SESSION]

export const getCurrentWallet = createSelector(
  getDuckSession,
  (session) => {
    const { currentWallet } = session
    return currentWallet
  },
)
```

In very rare case we may want to have whole duck in JSX (in other ducks). in this case
```
const getDuckSession = (state) =>
  state[DUCK_SESSION]
```
became
```
export const getDuckSession = (state) =>
  state[DUCK_SESSION]
```

2018-11-20 12:02 UTC, ozalexo commented on src/redux/session/thunks.js
> +export const Login = (currentWallet) => async (dispatch) => {
Let's add async when we really will have await.

2018-11-20 12:08 UTC, e-molochko commented on src/redux/session/constants.js
> +export const USER_ACTIONS = {
So mb it better to have an object of constants so our import will look as one row?

2018-11-21 07:06 UTC, ozalexo requested changes

2018-11-21 07:06 UTC, ozalexo commented on src/screens/Login/Start/StartContainer.js
> +    store.dispatch(loginThunk('0xf1106d1eb597ef2f14c8f5343c1b4203fa0f2e9b')) //check login
As far as I can see, these changes at lines 36-37 only for testing purposes...

2018-11-21 07:06 UTC, ozalexo commented on src/screens/Login/Start/StartContainer.js
> +import { loginThunk, logoutThunk } from '../../../redux/session/thunks'
logoutThunk only for testing purposes?

2018-11-21 07:22 UTC, ozalexo approved these changes

2018-11-21 07:22 UTC, merged